package:
    name: sync_app
    version: "0.0.2.1"

#build:
    #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../

requirements:
  build:
    - python
    - numpy
    - libpython # [py2k and win]
    - sqlalchemy
    - google-api-python-client
    - boto

  run:
    - python
    - numpy
    - google-api-python-client
    - boto

test:
  imports:
    - sync_app

  requires:
    - nose

  commands:
    - nosetests sync_app

#about
  #home: http://pandas.pydata.org
  #license: BSD
